// SPDX-FileCopyrightText: © 2025 Ethaks <ethaks@pm.me>
//
// SPDX-License-Identifier: LicenseRef-CopyrightEthaks

import { staticID } from "@helpers/utils.mjs";

/** @import { ActorRollOptions } from "../dice/roll" */

/**
 * @extends {Actor}
 */
export class CurseborneActor extends foundry.documents.Actor {
	/**
	 * Augment the actor's default getRollData() method by appending the data object
	 * generated by the its DataModel's getRollData(), or null. This polymorphic
	 * approach is useful when you have actors & items that share a parent Document,
	 * but have slightly different data preparation needs.
	 *
	 * @inheritDoc
	 */
	getRollData() {
		return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
	}

	/** @inheritDoc */
	applyActiveEffects() {
		super.applyActiveEffects();

		// Manually add modifiers from statuses to AEs providing them;
		// this ensures that each status's modifiers are only applied once, while keeping them connected to their source AE
		if (this.statuses.size) {
			for (const status of this.statuses) {
				const activeEffect =
					this.effects.get(staticID(`curse${status}`)) ??
					this.allApplicableEffects().find((e) => e.active && e.statuses.has(status));
				if (activeEffect) {
					for (const modifierType of ["enhancements", "complications", "difficulties"]) {
						for (const [modifierId, modifier] of Object.entries(
							curseborne.config.STATUS_EFFECTS[status]?.[modifierType] ?? {},
						)) {
							const cls = activeEffect.system.schema.fields[modifierType].model.model;
							const data = foundry.utils.deepClone(modifier);
							data.id = modifierId;
							data.label = game.i18n.has(modifier.label)
								? game.i18n.localize(modifier.label)
								: activeEffect.name;
							data.hint = game.i18n.has(modifier.hint) ? game.i18n.localize(modifier.hint) : "";
							activeEffect.system[modifierType].set(
								modifierId,
								new cls(data, { parent: activeEffect.system }),
							);
						}
					}
				}
			}
		}
	}
}
